spring:
  application:
    name: store-product
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/store}
    username: ${DATABASE_USERNAME:store}
    password: ${DATABASE_PASSWORD:store123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: product
  jpa:
    properties:
      hibernate:
        default_schema: product

management:
  endpoints:
    web:
      base-path: /products/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}


springdoc:
  api-docs:
    path: /products/v3/api-docs
  swagger-ui:
    path: /products/swagger-ui.html
  version: 3.0.0
