apiVersion: v1
kind: Service
metadata:
    name: product
    labels:
        name: product
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    selector:
        app: auth