apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    name: product
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: product